<a href="https://colab.research.google.com/github/20104047TranThiMyNgoc/AI-Subject/blob/main/Tu%E1%BA%A7n5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[10,0],[1,0],[0,1],[1,1]]
y=[0,1,1,1]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))
x_test=[[0.5,0],[0.9,-0.2],[1,-0.5],[0.2,0.7]]
y_test=model.predict(x_test)
print(y_test)

do chinh xac 1.0
[1 1 0 1]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
x=[[-0.5,-0.5],[-0.5,0.5],[0.3,-0.5],[-0.1,1]]
y=[1,1,0,0]
model=Perceptron()
model.fit(x,y)
print('do chinh xac',model.score(x,y))
x_test=[[0,1],[1,0],[0,0],[0,0]]
y_test=model.predict(x_test)
print(y_test)

do chinh xac 1.0
[0 0 0 0]


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split
import pandas as pd
url='/content/crabs.csv'
data= pd.read_csv(url)
data = data[:95]
data.loc[data['sex']=='M','sex']='1'
data.loc[data['sex']=='F','sex']='0'
data[(data['speies']=='B')]
x=data.drop(['speies','sex'],axis=True)    #bo di loài, giới tính
y=data['sex']#giới tính
model=Perceptron()
model.fit(x,y)
print('độ chính xác',model.score(x,y))
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=10)
x_test = [[5,6,14,13,10,6],[8,12,7,23,30,15],[13,5,22,15,10,13],[19,12,15,20.3,11.5,22.6]] 
y_test = model.predict(x_test)
print(y_test)

độ chính xác 0.9894736842105263
['0' '1' '0' '0']


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"


In [ ]:
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.model_selection import train_test_split 
from sklearn.datasets import load_iris
import pandas as pd
url = '/content/iris.csv'
data = pd.read_csv(url)
data = data[:95]
x= data.drop(['variety'],axis = 1)
y= data['variety'].replace(['Setosa','Versicolor','Virginica'],[1,0,0])
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.3)
model = Perceptron()
model.fit(x_train,y_train)
print('Độ chính xác_BT2:', model.score(x_train,y_train))
x_vao = [[5.3,2,4,1.2],[5,2,1.5,0.8],[6,5,1.8,0.5]]
y_ra = model.predict(x_vao)
print(y_ra)

Độ chính xác_BT2: 1.0
[0 1 1]


/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but Perceptron was fitted with feature names
  "X does not have valid feature names, but"
